name: Docker Image CI
on:
 push:
    branches: [ "master" ]
 pull_request:
    branches: [ "master" ]
jobs:
  build:
     runs-on: ubuntu-latest
     strategy:
       matrix:
         node-version: [18.16.0]
     steps:
       - uses: actions/checkout@v3
       - name: Use Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v1
         with:
           node-version: ${{ matrix.node-version }}
       - name: Install Dependencies
         run: npm i -g yarn && yarn
       - name: Build
         run: yarn build
       - uses: docker/login-action@v3
         with:
           registry: ghcr.io # 声明镜像源
           username: ${{ secrets.DOCKERHUB_USERNAME }}  # 当前github 用户名
           password: ${{ secrets.HUB_GITHUB_TOKEN }}  #需要去 https://github.com/settings/tokens 生成一个 名为 token，注意此token 需要读写 packages 等权限
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
       - name: Build and push Docker image
         uses: : docker/build-push-action@v5
         with:
           context: .
           file: ./Dockerfile
           push: true
           tags: yuanshenliu/clockbox:latest
